#!/bin/bash

# install chef on a container using knife. assumes container name is accessible via network, and username/password is ubuntu

CONTAINER_NAME="$1"

EXPECTED_ARGS=1
if [ $# -ne $EXPECTED_ARGS ]; then
        echo "usage"
        echo "-----"
	echo "specify install_chef CONTAINER_NAME"
 	exit 1
fi

ssh ubuntu@$CONTAINER_NAME -C "sudo apt-get install -y wget curl ca-certificates" 

bundle exec knife bootstrap "$CONTAINER_NAME" -x ubuntu -P ubuntu --sudo --use-sudo-password ubuntu
