#!/bin/bash

# install chef on a container using knife. assumes container name is accessible via network, and username/password is ubuntu

CONTAINER_NAME="$1"

EXPECTED_ARGS=1
if [ $# -ne $EXPECTED_ARGS ]; then
        echo "usage"
        echo "-----"
	echo "specify install_chef CONTAINER_NAME"
 	exit 1
fi

ssh ubuntu@$CONTAINER_NAME -C "sudo apt-get update" 
ssh ubuntu@$CONTAINER_NAME -C "sudo apt-get install -y --force-yes wget curl ca-certificates apt-transport-https aptitude" 
ssh ubuntu@$CONTAINER_NAME -C "sudo locale-gen en_US en_US.UTF-8" 
ssh ubuntu@$CONTAINER_NAME -C "sudo dpkg-reconfigure locales" 
ssh ubuntu@$CONTAINER_NAME -C "sudo apt-get install incron" 

# install chef 11.8.2 debian for ubuntu 12.04
ssh ubuntu@$CONTAINER_NAME -C "wget https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef_11.8.2-1.ubuntu.12.04_amd64.deb && sudo dpkg -i chef_11.8.2-1.ubuntu.12.04_amd64.deb"
